### PR TITLE
Node.js stuffs

### PR DESCRIPTION
**Pull request by EpicPuppy613**
- add npm package
- add npm scripts
- add back to home button to test.html
- add github codespaces configuration

### CODE REVIEW

**Comment by Cattn** [comment]
Why add node packages to the repo?

**Comment by EpicPuppy613** [comment]
it's not node package it's initializing the repo as a node package and adding scripts

**Comment by Cattn** [comment]
Nvm I didn't actually look at the commit lol

**Comment by EpicPuppy613** [comment]
> Why add node packages to the repo?

it already has a bunch of node packages

**Comment by Cattn** [comment]
Strike 1. Your fired @EpicPuppy613

**Comment by EpicPuppy613** [comment]
> Test.html already has back to index

it's not clear tho

**Comment by EpicPuppy613** [comment]
> Strike 1. Your fired @EpicPuppy613

I wasn't hired in the first place either

**Comment by Cattn** [comment]
Exactly you got fired before you were hired, very impressive

**Comment by Cattn** [comment]
> > Test.html already has back to index
> 
> it's not clear tho

Not clear is our middle name if you didn't know

**Comment by JavaScythe** [comment]
@Cattn stop mesing with him

**Comment by Cattn** [comment]
> @Cattn stop mesing with him

My bad I'll spill the news, @EpicPuppy613 your hired for the project!

**Comment by EpicPuppy613** [comment]
> > @Cattn stop mesing with him
> 
> My bad I'll spill the news, @EpicPuppy613 your not yet hired for the project!
> 
> Edit: corrected mistake

*you're

**Comment by EpicPuppy613** [comment]
how secure is this github discord bot anyway

**Comment by EpicPuppy613** [comment]
<@1074787688227536906>

**Comment by Cattn** [comment]
> how secure is this github discord bot anyway

??? GitHub/discord it's just a web hook integration that they support natively

**Comment by EpicPuppy613** [comment]
<@523927057722376204>

**Comment by EpicPuppy613** [comment]
<@523927057722376204> ping
<@523927057722376204> ping
<@523927057722376204> ping

**Comment by EpicPuppy613** [comment]
too bad

**Comment by EpicPuppy613** [comment]
wait do animated emotes work

**Comment by EpicPuppy613** [comment]
time to find out :trollface:

**Comment by EpicPuppy613** [comment]
<a:partyblob:900580388970319914:>

**Comment by EpicPuppy613** [comment]
rip doesn't work

**Comment by EpicPuppy613** [comment]
<a:partyblob:900580388970319914>

**Comment by Cattn** [comment]
😱😿😊😿💔🙅‍♀️🤸😿🌍🔍💅🔍💔🤸😇😹💀😹🙏🐟🔍🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟☠️☠️☠️☠️☠️❤️🙂🙅‍♀️❤️🐟😇🐟😇🐟

**Comment by EpicPuppy613** [comment]
bruh you have custom emotes turned off for the bot

**Comment by EpicPuppy613** [comment]
<:the:950530817669607474>

**Comment by EpicPuppy613** [comment]
<:the:950530817669607474><:the:950530817669607474><:the:950530817669607474>

**Comment by EpicPuppy613** [comment]
<:epicpuppy:1061496767046226040>

**Pull request closed without merging**
